package neshto.fiatbot.screen

enum class ScreenName {
    GUEST_HELLO,
    TRADER_MAIN,
    REGISTRATION,
    REGISTRATION_COMPLETED,
    INFO,
    WALLET,
    CREATE_WALLET,
    FILL_UP_WALLET,

    CHANGE,

    CHANGE_SELECT_CURRENCY,
    CHANGE_SELECT_PAYWAY,
    CHANGE_ADVERTS_LIST,

    ADVERT_VIEW,
    DEAL_ENTER_AMOUNT,
    DEAL_PURCHASE_APPROVE_AMOUNT,
    DEAL_SELL_APPROVE_AMOUNT,
    DEAL_MONEY_SEND,
    DEAL_MONEY_WAIT,
    DEAL_CANCELED_SELLER,
    DEAL_CANCELED_BUYER,
    DEAL_MONEY_SENT_SELLER,
    DEAL_MONEY_SENT_BUYER,
    DEAL_COINS_SENT_SELLER,
    DEAL_COINS_SENT_BUYER,

    CREATE_ADVERT_SELECT_TYPE,
    CREATE_ADVERT_SELECT_CURRENCY,
    CREATE_ADVERT_SELECT_PAYWAY,
    CREATE_ADVERT_ENTER_COURSE,
    CREATE_ADVERT_ENTER_LIMITS,
    CREATE_ADVERT_APPROVE,

    TRADER_INFO,
    SEND_MESSAGE,
    MESSAGE,
    MESSAGE_SENT,

    APP_WALLET,

    ERROR
}