package neshto.fiatbot.screen.menuaction

enum class MenuActionName {
    REGISTRATION,
    CONFIRM_REGISTRATION,
    GOTO_BEGINNING,
    WALLET,
    INFO,

    CHANGE,

    ADMIN_RELOAD_CONFIG,
    ADMIN_VIEW_WALLETS,

    // Создание объявления
    CREATE_ADVERT_SELECT_CURRENCY_BTC,

    CREATE_ADVERT_SELECT_PURCHASE,
    CREATE_ADVERT_SELECT_SELL,

    CREATE_ADVERT_SELECT_PAYWAY_SBER,
    CREATE_ADVERT_SELECT_PAYWAY_TINKOFF,
    CREATE_ADVERT_SELECT_PAYWAY_QIWI,

    CREATE_ADVERT_APPROVE,
    CREATE_ADVERT_CANCEL,

    // Сделка
    DEAL_APPROVE,
    DEAL_CANCEL
}